
// Constants
const INIT_MSG = 'INIT_MSG';export const COUNTER_CTRL_SET_INCREMENT_BY = 'COUNTER_CTRL_SET_INCREMENT_BY';
export const COUNTER_CTRL_INCREMENT = 'COUNTER_CTRL_INCREMENT';
export const COUNTER_MODEL_INCREMENT = 'COUNTER_MODEL_INCREMENT';
export const EXECUTE_NEXT_MSG = 'EXECUTE_NEXT_MSG';

