
// Constants
const INIT_MSG = 'INIT_MSG';
export const COUNTER_CTRL_SET_INCREMENT_BY = 'COUNTER_CTRL_SET_INCREMENT_BY';
export const ANOTHER_COUNTER_CTRL_SET_INCREMENT_BY = 'ANOTHER_COUNTER_CTRL_SET_INCREMENT_BY';
export const COUNTER_CTRL_INCREMENT = 'COUNTER_CTRL_INCREMENT';
export const ANOTHER_COUNTER_CTRL_INCREMENT = 'ANOTHER_COUNTER_CTRL_INCREMENT';
export const COUNTER_MODEL_INCREMENT = 'COUNTER_MODEL_INCREMENT';
export const INDEPENDENT_COUNTER_CTRL_SET_INCREMENT_BY = 'INDEPENDENT_COUNTER_CTRL_SET_INCREMENT_BY';
export const INDEPENDENT_COUNTER_CTRL_INCREMENT = 'INDEPENDENT_COUNTER_CTRL_INCREMENT';
export const INDEPENDENT_COUNTER_MODEL_INCREMENT = 'INDEPENDENT_COUNTER_MODEL_INCREMENT';


