import { APP_OUTPUT_PATH_SEGMENTS } from '../constants';

// Model
export const ACCUMULATOR_MODEL_INCREMENT = 'ACCUMULATOR_MODEL_INCREMENT';
export const ACCUMULATOR_MODEL_INIT = 'ACCUMULATOR_MODEL_INIT';

// Controller
export const ACCUMULATOR_CONTROLLER_INCREMENT = 'ACCUMULATOR_CONTROLLER_INCREMENT';
export const ACCUMULATOR_CONTROLLER_SET_INCREMENT_BY = 'ACCUMULATOR_CONTROLLER_SET_INCREMENT_BY';
export const ACCUMULATOR_CONTROLLER_DUMP = 'ACCUMULATOR_CONTROLLER_DUMP';
export const APP_OUTPUT_PATH_SEGMENTS_GLOBAL_ACCUMULATOR = APP_OUTPUT_PATH_SEGMENTS.concat('globalAccumulator');export const APP_OUTPUT_PATH_SEGMENTS_ACCUMULATOR = APP_OUTPUT_PATH_SEGMENTS.concat('accumulator');
export const APP_OUTPUT_PATH_SEGMENTS_ACCUMULATOR_INCREMENT_BY = APP_OUTPUT_PATH_SEGMENTS.concat('accumulatorIncrementBy');

