// Model
export const ACCUMULATOR_MODEL_INCREMENT = 'ACCUMULATOR_MODEL_INCREMENT';
export const ACCUMULATOR_MODEL_INIT = 'ACCUMULATOR_MODEL_INIT';

// Controller
export const ACCUMULATOR_CONTROLLER_INCREMENT = 'ACCUMULATOR_CONTROLLER_INCREMENT';
export const ACCUMULATOR_CONTROLLER_SET_INCREMENT_BY = 'ACCUMULATOR_CONTROLLER_SET_INCREMENT_BY';
export const ACCUMULATOR_CONTROLLER_DUMP = 'ACCUMULATOR_CONTROLLER_DUMP';