import { APP_DATA_PATH, APP_OUTPUT_PATH_SEGMENTS, APP_STATE_PATH } from '../constants';

// Model
export const ACCUMULATOR_MODEL_INCREMENT = 'ACCUMULATOR_MODEL_INCREMENT';
export const ACCUMULATOR_MODEL_INIT = 'ACCUMULATOR_MODEL_INIT';

// Controller
export const ACCUMULATOR_CONTROLLER_INCREMENT = 'ACCUMULATOR_CONTROLLER_INCREMENT';
export const ACCUMULATOR_CONTROLLER_SET_INCREMENT_BY = 'ACCUMULATOR_CONTROLLER_SET_INCREMENT_BY';
export const ACCUMULATOR_CONTROLLER_DUMP = 'ACCUMULATOR_CONTROLLER_DUMP';

// State
export const ACCUMULATOR_CONTROLLER_STATE_PATH = `${APP_STATE_PATH}.accumulatorComponent`;
export const ACCUMULATOR_CONTROLLER_STATE_PATH_SEGMENTS = ACCUMULATOR_CONTROLLER_STATE_PATH.split('.');

// Output
export const APP_OUTPUT_PATH_SEGMENTS_GLOBAL_ACCUMULATOR = APP_OUTPUT_PATH_SEGMENTS.concat('globalAccumulator');

export const APP_OUTPUT_PATH_SEGMENTS_ACCUMULATOR = APP_OUTPUT_PATH_SEGMENTS.concat('accumulator');
export const APP_OUTPUT_PATH_SEGMENTS_ACCUMULATOR_INCREMENT_BY = APP_OUTPUT_PATH_SEGMENTS.concat('accumulatorIncrementBy');
export const ACCUMULATOR_COMPONENT_STATE_PATH = APP_STATE_PATH + '.accumulatorComponent';
export const ACCUMULATOR_VALUE_DATA_PATH = APP_DATA_PATH + '.accumulator';
export const ACCUMULATOR_VALUE_DATA_PATH_SEGMENTS = ACCUMULATOR_VALUE_DATA_PATH.split('.');
export const COMPONENT_ACCUMULATOR_PATH = ACCUMULATOR_COMPONENT_STATE_PATH + '.accumulator';
export const COMPONENT_ACCUMULATOR_INCREMENT_BY_PATH = ACCUMULATOR_COMPONENT_STATE_PATH + '.incrementBy';
export const COMPONENT_ACCUMULATOR_INCREMENT_BY_DATA_PATH_SEGMENTS = COMPONENT_ACCUMULATOR_INCREMENT_BY_PATH.split('.');

